### ISSUE TITLE
NodeJS 16 Actions are deprecated: Upgrade to Node Version 20

### ISSUE THREAD

**Issue by md-weber** [VeryGoodOpenSource/very_good_coverage#309]
**Is your feature request related to a problem? Please describe.**
We currently receive the warning that we should make sure to only use actions with a LTS node version (20) and get the following warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: VeryGoodOpenSource/very_good_coverage@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Describe the solution you'd like**
Upgrade to node 20

**Describe alternatives you've considered**

**Additional context**

**Comment by tomarra** [comment]
Should be fixed by #310 once we do a release.

**Comment by tomarra** [comment]
This should be fixed by the v3.0.0 release. If not lets open a new ticket with new steps & details.

**Comment by md-weber** [comment]
Fantastic, thanks for your hard work!
