### ISSUE TITLE
Parsing Error!

### ISSUE THREAD

**Issue by pradyotprksh** [VeryGoodOpenSource/very_good_coverage#36]
**Describe the bug**
When the GitHub action starts it gives an error with message

Error: parsing error!

I used the below workflow option

- uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 1

**Comment by pradyotprksh** [comment]
<img width="913" alt="Screenshot 2021-03-20 at 7 34 58 PM" src="https://user-images.githubusercontent.com/35835404/111872118-b09a8500-89b3-11eb-95c9-8f300e931dd9.png">

**Comment by jorgecoca** [comment]
Hi @pradyotprksh 👋  Thank you for opening an issue!

Would you mind sharing with us the command you are using to generate the `lcov.info`? Even better as well, if you could also share with us the content of the `lcov.info` file it could help us to better pinpoint the issue.

Thank you!

**Comment by pradyotprksh** [comment]
Okay @jorgecoca I think I am making mistake while integrating it. Will close this for now. If any issues will reopen it.
