### ISSUE TITLE
[proposal] snippet for gitlab

### ISSUE THREAD

**Issue by aoatmon** [VeryGoodOpenSource/very_good_coverage#43]
**Is your feature request related to a problem? Please describe.**
my company uses gitlab, is there a way to use `very_good_coverage` in gitlanCI ?

**Describe the solution you'd like**
A snippet to add in gitlab's yaml

**Describe alternatives you've considered**
look elsewhere

**Comment by jorgecoca** [comment]
Hi @aoatmon 👋 

Really good question! As of now, `very_good_coverage` is strictly a GitHub Action written in JS; however, in the past, we also created this [lcov-cop](https://github.com/ChicagoFlutter/lcov-cop) solution. You can get the necessary bash script from `entrypoint.sh` and use it on Gitlab.

**Comment by aoatmon** [comment]
@jorgecoca 
thank you, I'll try it out
closing for now
