### ISSUE TITLE
A new feature to ensure that the coverage doesn't go down

### ISSUE THREAD

**Issue by NaagAlgates** [VeryGoodOpenSource/very_good_coverage#65]
**Is your feature request related to a problem? Please describe.**
Along with `min_coverage`, we can also add a new boolean to allow or not to allow the CI to proceed further when the percentage is decreased.

For Example:
`min_coverage` is set to 25%. In my 4th Pull Request, I have achieved 30% coverage. In my 5th Pull request, I have gone down to 28%. Though I'm legally above the `min_coverage`, yet the last PR has gone down by 2%. 

**Describe the solution you'd like**
We need to have a new boolean variable like `can_decrease` (or any other name 😄 ). By default, we can set it to `true`.  But if it is set to `false`, we should not allow the CI to build further because my latest PR's percentage has gone down by 2%.

**Additional context**
We need to store the percentage of each build and compare if is percentage has gone up or down. I'm not sure if that's a viable option but thought it would be nice to have a feature like this.

**Comment by felangel** [comment]
Hi @NaagAlgates 👋 
We recommend continuing to increase the `min_coverage` value as you add tests in order to ensure the coverage does not decrease rather than adding a new input.

**Comment by NaagAlgates** [comment]
Thank you @felangel
